sketch_params:
  cms:
    width: 1000
    depth: 5
  kll:
    k: 200
  reservoir:
    size: 1000

experiments:
  stream_sizes: [10000, 100000, 1000000]
  quantiles: [0.1, 0.25, 0.5, 0.75, 0.9]
  heavy_hitter_threshold: 0.01 # 1% of stream size
